# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.IntegerField()),
                ('licance_id', models.IntegerField()),
                ('licence_exp', models.DateField()),
                ('fitness_id', models.IntegerField()),
                ('fitness_exp', models.DateField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
